name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: raferdev/github-profile-3d-contrib@3.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name NekoHanaku
          git config user.email 94982112+NekoHanaku@users.noreply.github.com
          git add -A .
          git commit -m "Updated Profile"
          git push
